version: 0.0
os: ubuntu
files:
  - source: /
    destination: /var/www/html/blog
permissions:
   - object: /var/www/html/blog
     pattern: "**"
     owner: apache
     group: apache
     mode: 755
     type:
       - file
hooks:
  AfterInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
