version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/blog
permissions:
   - object: /var/www/html
     pattern: "**"
     owner: apache
     group: apache
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
 
   AfterInstall:
